#!/usr/bin/env bash
#
# Creates users massively, reding from file
#
# Author: Luca Giugliardi
# Email: luca.giugliardi@gmail.com

# ----------------------------- Shell Options ----------------------------

set -o pipefail

# ------------------------------- Functions ------------------------------

get_lib_path() {
	local lib_path
	lib_path=$(cd "$(dirname "$0")" && echo "${PWD}" | sed 's/\/[^/]*$/\/lib/')
	echo "${lib_path}"
}

main() {
	local username
	local password
	local group
	local description
	local shell

	while IFS=: read -r username password group description shell; do
		shell=${shell:-bash}
		shell_path=$(which "$shell")
		password=${password:-TempPassword#01}

		print_color "blue" "Creating user $username"

		if [ -z "$group" ]; then
			useradd -c "$description" -d "/home/$username" -s "$shell_path" "$username"
		else
			useradd -G "$group" -c "$description" -d "/home/$username" -s "$shell_path" "$username"
		fi

		print_color "green" "User $username succesfully created"

		print_color "blue" "Setting $username initial password"

		echo -e "$password\n$password\n" | passwd --stdin "$username"
		passwd --expire "$username"

		print_color "green" "Set password for user $username"

	done <"$1"
	unset IFS
}

# -------------------------------- Imports -------------------------------

lib_path=$(get_lib_path)

# shellcheck source=/dev/null

source "${lib_path}/print-color.sh"

# ----------------------------- Users Creation ---------------------------

main users-list.txt
